<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Place;

class PlaceSeeder extends Seeder
{
    public function run()
    {
        $places = [
            ['name' => 'Ambalangoda Beach', 'cat' => 'Beach & Relaxation', 'dist' => '0 km', 'emoji' => '🏖️', 'bg' => '#EBF3F9', 'lat' => 6.2333, 'lng' => 80.0500, 'desc' => 'Ambalangoda Beach is a pristine, relatively uncrowded stretch of golden sand known for its relaxing atmosphere and scenic sunsets. Unlike busier tourist hubs, this beach offers a tranquil environment perfect for long, quiet walks and watching local fishermen. While ocean currents can sometimes be strong, natural rock pools form during low tide, offering safe, shallow areas for quick dips.', 'hours' => 'Open 24 hours', 'fee' => 'Free entry', 'transport' => 'Walking distance from town center', 'season' => 'November – April'],
            ['name' => 'Sri Vijayarama Viharaya', 'cat' => 'Culture & History', 'dist' => '~2 km', 'emoji' => '🛕', 'bg' => '#FAF0EA', 'lat' => 6.2400, 'lng' => 80.0600, 'desc' => 'Sri Vijayarama Viharaya is a spiritually and historically significant Buddhist temple serving the Ambalangoda community. The temple grounds feature magnificent Buddha statues, intricate mural paintings depicting Jataka tales, and a serene Bodhi tree. It serves as a peaceful retreat for meditation and observing traditional Sri Lankan religious practices away from the bustling town center.', 'hours' => '6:00 AM – 8:00 PM', 'fee' => 'Free (donations welcome)', 'transport' => 'Tuk-tuk from town (~LKR 150)', 'season' => 'Year-round'],
            ['name' => 'Ambalangoda Mask Museum', 'cat' => 'Culture & History', 'dist' => '~1 km', 'emoji' => '🎭', 'bg' => '#FAF0EA', 'lat' => 6.2380, 'lng' => 80.0520, 'desc' => 'Ambalangoda is globally renowned as the heart of Sri Lankan mask carving and devil dancing (Kolam). The Ariyapala Mask Museum features an extensive, fascinating collection of vibrant wooden masks, each possessing unique cultural origins used in traditional healing rituals AND folklore dramas. Visitors can watch master artisans meticulously hand-carving and painting masks using traditional Kaduru wood and natural dyes.', 'hours' => '8:00 AM – 5:30 PM', 'fee' => 'LKR 500 (adults)', 'transport' => 'Walking distance or tuk-tuk', 'season' => 'Year-round'],
            ['name' => 'Madu Ganga River Safari', 'cat' => 'Nature & Wildlife', 'dist' => '~5 km', 'emoji' => '🛶', 'bg' => '#EAF1EC', 'lat' => 6.2750, 'lng' => 80.0380, 'desc' => 'The Madu Ganga is a complex coastal wetland ecosystem and a Ramsar-recognized site boasting immense biodiversity. A boat safari glides through dense mangrove tunnels covering dozens of small islands, offering sightings of water monitors, kingfishers, and crocodiles. The tour typically includes stops at historical island temples and local cinnamon-peeling farms, providing a truly immersive ecological and cultural experience.', 'hours' => '6:00 AM – 6:00 PM', 'fee' => 'LKR 2,500–3,500 (boat hire)', 'transport' => 'Tuk-tuk (~LKR 300)', 'season' => 'Year-round'],
            ['name' => 'Kosgoda Turtle Hatchery', 'cat' => 'Nature & Wildlife', 'dist' => '~8 km', 'emoji' => '🐢', 'bg' => '#EAF1EC', 'lat' => 6.3110, 'lng' => 80.0070, 'desc' => 'Located just north of Ambalangoda, Kosgoda is famous for its pioneering sea turtle conservation projects. The hatcheries patrol the beaches to rescue fragile turtle eggs from predators and poachers, safely incubating them until they hatch. Visitors get the rare opportunity to see endangered species like the Olive Ridley and Leatherback turtles up close, and can even participate in releasing newly hatched baby turtles into the ocean at dusk.', 'hours' => '7:00 AM – 6:00 PM', 'fee' => 'LKR 500 (adults)', 'transport' => 'Bus or tuk-tuk from Ambalangoda', 'season' => 'Year-round'],
            ['name' => 'Meetiyagoda Moonstone Mine', 'cat' => 'Nature & Wildlife', 'dist' => '~10 km', 'emoji' => '💎', 'bg' => '#EAF1EC', 'lat' => 6.2080, 'lng' => 80.0890, 'desc' => 'Meetiyagoda is one of the few places on Earth where the rare, alluring blue-glowing moonstone is found. Visitors can take a guided, educational tour to see the entire primitive mining process, starting from the deep, waterlogged muddy shafts where miners hand-dig the rough stones. The tour concludes by showing the intricate washing, cutting, and polishing processes that transform the raw stones into exquisite jewelry.', 'hours' => '8:00 AM – 5:00 PM', 'fee' => 'Free entry', 'transport' => 'Tuk-tuk (~LKR 500)', 'season' => 'Year-round'],
            ['name' => 'Hikkaduwa Beach', 'cat' => 'Adventure & Activities', 'dist' => '~12 km', 'emoji' => '🤿', 'bg' => '#FDF6E6', 'lat' => 6.1400, 'lng' => 80.0980, 'desc' => 'Hikkaduwa is a vibrant, bustling coastal town famous for its pristine coral sanctuary and surf-friendly waves. The shallow, crystal-clear waters make it an absolute paradise for snorkeling and scuba diving, where visitors can easily spot colorful reef fish and giant sea turtles swimming close to the shore. Beyond the water sports, the beach is lined with lively seafood restaurants, cafes, and a bustling nightlife scene.', 'hours' => 'Open 24 hours', 'fee' => 'Free (water sports extra)', 'transport' => 'Bus from Ambalangoda (~LKR 50)', 'season' => 'November – April'],
            ['name' => 'Lunuganga Gardens', 'cat' => 'Culture & History', 'dist' => '~15 km', 'emoji' => '🌸', 'bg' => '#FAF0EA', 'lat' => 6.4020, 'lng' => 80.0080, 'desc' => 'Lunuganga is the enchanting country estate of the late Geoffrey Bawa, Sri Lanka\'s most celebrated architect and the pioneer of \'tropical modernism\'. Set on the banks of Dedduwa Lake, the estate is an architectural masterpiece seamlessly blending European Renaissance garden designs with lush tropical flora. A guided tour walks visitors through perfectly framed vistas, terraced gardens, and open pavilions that deeply inspired Bawa’s life\'s work.', 'hours' => '9:00 AM – 5:00 PM', 'fee' => 'LKR 1,500 (adults)', 'transport' => 'Tuk-tuk or hired car', 'season' => 'Year-round'],
            ['name' => 'Galle Fort', 'cat' => 'Culture & History', 'dist' => '~20 km', 'emoji' => '🏰', 'bg' => '#FAF0EA', 'lat' => 6.0270, 'lng' => 80.2170, 'desc' => 'Originally built by the Portuguese in 1588 and extensively fortified by the Dutch in the 17th century, Galle Fort is an architectural marvel and a UNESCO World Heritage Site. Enclosed by massive stone ramparts overlooking the Indian Ocean, the fort is virtually a living museum. Its charming cobblestone streets are lined with beautifully preserved colonial-era buildings, boutique hotels, art galleries, and cafes, offering a perfect blend of rich history and modern luxury.', 'hours' => 'Open 24 hours (ramparts)', 'fee' => 'Free (museum entry extra)', 'transport' => 'Bus or train from Ambalangoda', 'season' => 'Year-round'],
            ['name' => 'Bentota Beach', 'cat' => 'Beach & Relaxation', 'dist' => '~22 km', 'emoji' => '🌅', 'bg' => '#EBF3F9', 'lat' => 6.4250, 'lng' => 79.9960, 'desc' => 'Bentota is a premier resort destination characterized by a spectacular, broad stretch of golden sandy beach shaded by tall palm trees. It uniquely forms a peninsula separating the Indian Ocean from the Bentota Lagoon, making it the undisputed water sports capital of Sri Lanka. Visitors can enjoy thrilling activities ranging from jet-skiing and windsurfing on the lagoon to relaxing sunset cruises along the serene beachfront.', 'hours' => 'Open 24 hours', 'fee' => 'Free (water sports extra)', 'transport' => 'Train from Ambalangoda (~LKR 80)', 'season' => 'November – April']
        ];

        foreach ($places as $place) {
            Place::create($place);
        }
    }
}
